### ISSUE TITLE
Add Custom Layouts

### ISSUE THREAD

**Issue by darkwood-studios** [StarkSoftware/SSForms#3]
Hi there,

I'm looking for a possibility to change the layouts for the form fields.

For example I want to move the title/label from left to above and add some additional padding to the items.

Looking forward to your feedback.

**Comment by StarkSoftware** [comment]
Hi, you can override the XML layout of form fields in your project.
Example : 
https://github.com/StarkSoftware/SSForms/blob/master/ssForm/src/main/res/layout/form_element.xml

you can create in your project res/layout/form_element.xml 
and the library override the default layout with yours.
